apiVersion: v1
kind: Pod
metadata:
  name: kafka-cli
  namespace: knative-eventing
spec:
  containers:
  - image: kafka-cli
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
